### ISSUE TITLE
Is there a limit to the number of times a link preview can be used in our app a given day

### ISSUE THREAD

**Issue by reginaldBarnabas** [winhtaikaung/react-tiny-link#14]
is it the proxy URL from herokuapp that limits it? 
All of a sudden today my app showing the preview for a link. i had to reinstall the plugin. 
Want to know how I can use this seamlessly. thanks a lot.

**Comment by winhtaikaung** [comment]
Hi @reginaldBarnabas yes it happens when the herokuapp become busy,
but you can build your own proxy server like `https://cors-anywhere.herokuapp.com` and host it on your own infra and pass your proxy server url to your component. 

For more detail you may look this repo which is the original source of this `https://cors-anywhere.herokuapp.com`
https://github.com/Rob--W/cors-anywhere

Thanks
